services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    user: 1000:1000
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - video
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_LOCATION}/jellyfin-config:/config
      - ${CONFIG_LOCATION}/jellyfin-cache:/cache
      - ${DATA_LOCATION}:/data
    # expose:
    #   - "8096"
    networks:
      - proxy_net

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports: # Expose qBittorrent's web UI and torrent ports through VPN
      # - 8700:8096   # Jellyfin
      - 8701:8701   # qBittorrent Web UI
      - 6881:6881   # torrent port
      - 6881:6881/udp
      - 7878:7878   # Radarr
      - 8989:8989   # Sonarr
      - 8686:8686   # Lidarr
      - 6767:6767   # Bazarr
      - 9696:9696   # Prowlarr
      - 8191:8191   # FlareSolverr
      # - 5055:5055   # Jellyseerr
    volumes:
      - ${CONFIG_LOCATION}/gluetun:/gluetun
      # - ./gluetun/us-den.conf:/gluetun/wireguard/wg0.conf
    environment:
      - VPN_TYPE=wireguard
      - VPN_SERVICE_PROVIDER=protonvpn
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=Sri Lanka
      - TZ=${TIMEZONE}
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"  # Routes all traffic through Gluetun
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8701
      - WEBUI_ADDRESS=0.0.0.0
      - WEBUI_EXTERNAL_ACCESS=true
    volumes:
      - ${CONFIG_LOCATION}/qbittorrent:/config
      - ${DATA_LOCATION}:/data
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    network_mode: "service:gluetun"  # Routes all traffic through Gluetun
    depends_on:
      - gluetun
    # ports:
    #   - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_LOCATION}/radarr:/config
      - ${DATA_LOCATION}:/data

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    network_mode: "service:gluetun"  # Routes all traffic through Gluetun
    depends_on:
      - gluetun
    # ports:
    #   - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_LOCATION}/sonarr:/config
      - ${DATA_LOCATION}:/data

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    network_mode: "service:gluetun"  # Routes all traffic through Gluetun
    depends_on:
      - gluetun
    # ports:
    #   - 8686:8686
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_LOCATION}/lidarr:/config
      - ${DATA_LOCATION}:/data
    restart: unless-stopped

  # bazarr:
  #   image: lscr.io/linuxserver/bazarr
  #   container_name: bazarr
  #   restart: unless-stopped
  #   network_mode: "service:gluetun"  # Routes all traffic through Gluetun
  #   depends_on:
  #     - gluetun
  #   # ports:
  #   #   - 6767:6767
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=${TIMEZONE}
  #   volumes:
  #     - ${CONFIG_LOCATION}/bazarr:/config
  #     - ${DATA_LOCATION}:/data

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    restart: unless-stopped
    network_mode: "service:gluetun"  # Routes all traffic through Gluetun
    depends_on:
      - gluetun
    # ports:
    #   - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_LOCATION}/prowlarr:/config

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: "service:gluetun"  # Routes all traffic through Gluetun
    environment:
      - TZ=${TIMEZONE}
    depends_on:
      - gluetun
    # ports:
    #   - 8191:8191
    restart: unless-stopped

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    restart: unless-stopped
    user: 1000:1000
    environment:
      - LOG_LEVEL=debug
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_LOCATION}/jellyseerr:/app/config
    # expose:
    #   - "5055"
    depends_on:
      - gluetun
      - jellyfin
      - sonarr
      - radarr
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true