services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    restart: unless-stopped
    volumes:
      - ./jellyfin-config:/config
      - ./jellyfin-cache:/cache
      - ${DATA_LOCATION}:/media
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri  # For hardware acceleration (Intel/AMD)
    environment:
      - TZ=${TIMEZONE}